# Generated by Django 3.2.17 on 2023-04-08 19:26

from django.db import migrations
from django.db import models

import users.managers


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='events_organized',
            field=models.PositiveIntegerField(
                default=0,
                help_text='events organized',
                verbose_name='events organized',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='events_visited',
            field=models.PositiveIntegerField(
                default=0,
                help_text='events visited',
                verbose_name='events visited',
            ),
        ),
    ]
