# Generated by Django 3.2.17 on 2023-04-11 16:04

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion

import users.models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20230408_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        help_text='Will be rendered at 300px',
                        upload_to=users.models.UserAvatar.saving_path,
                        verbose_name='image',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        help_text='user profile pic',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='avatar_image',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'avatar image',
                'verbose_name_plural': 'avatar images',
                'default_related_name': 'avatar_image',
            },
        ),
    ]
