# Generated by Django 3.2.17 on 2023-04-09 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20230408_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        help_text='Will be rendered at 300x300 px',
                        upload_to=users.models.UserAvatar.saving_path,
                        verbose_name='thumbnail',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        help_text='event thumbnail',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
