# Generated by Django 3.2.17 on 2023-04-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_useravatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='event_search_distance',
            field=models.PositiveIntegerField(
                default=100,
                help_text='Distance(km) to search events in',
                verbose_name='event search distance',
            ),
        ),
    ]
