# Generated by Django 3.2.17 on 2023-04-16 09:12

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_alter_user_event_search_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='user',
            field=models.OneToOneField(
                blank=True,
                help_text='user profile pic',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='avatar_image',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
