# Generated by Django 3.2.17 on 2023-04-16 17:21

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_alter_useravatar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='Will be rendered at 300px',
                upload_to=users.models.UserAvatar.saving_path,
                verbose_name='image',
            ),
        ),
    ]
