# Generated by Django 3.2.17 on 2023-04-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feedback', '0002_alter_feedback_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.CharField(
                default='a@a.a', max_length=254, verbose_name='email'
            ),
        ),
    ]
