# Generated by Django 3.2.17 on 2023-04-16 06:34

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('feedback', '0003_feedback_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.CharField(
                default='default@default.default',
                max_length=254,
                verbose_name='email',
            ),
        ),
    ]
