# Generated by Django 3.2.17 on 2023-04-16 07:18

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('feedback', '0006_auto_20230416_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.CharField(
                help_text='Your email address',
                max_length=254,
                verbose_name='email *',
            ),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(
                help_text='Feedback message',
                max_length=200,
                verbose_name='message *',
            ),
        ),
    ]
