# Generated by Django 3.2.17 on 2023-04-16 08:01

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('feedback', '0007_auto_20230416_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(
                help_text='Your email address',
                max_length=254,
                verbose_name='email *',
            ),
        ),
    ]
