# Generated by Django 3.2.17 on 2023-04-09 11:03

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_alter_event_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={
                'ordering': ('date',),
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
        migrations.RenameField(
            model_name='event',
            old_name='datetime',
            new_name='date',
        ),
        migrations.CreateModel(
            name='EventThumbnail',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        help_text='Will be rendered at 300px',
                        upload_to='events/',
                        verbose_name='image',
                    ),
                ),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                (
                    'event',
                    models.ForeignKey(
                        blank=True,
                        help_text='event thumbnail',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='events.event',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventGallery',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        help_text='Will be rendered at 300px',
                        upload_to='events/',
                        verbose_name='image',
                    ),
                ),
                (
                    'gallery_images',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='event_gallery',
                        to='events.event',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Event Gallery Photo',
                'verbose_name_plural': 'Event Gallery Photos',
            },
        ),
        migrations.CreateModel(
            name='EventComment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'message',
                    models.TextField(
                        help_text='Write the comment here',
                        max_length=100,
                        verbose_name='comment',
                    ),
                ),
                (
                    'author',
                    models.ForeignKey(
                        help_text='comment author',
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'event',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='events.event',
                    ),
                ),
            ],
        ),
    ]
