# Generated by Django 3.2.17 on 2023-04-09 11:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0003_auto_20230409_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventthumbnail',
            name='name',
        ),
    ]
