# Generated by Django 3.2.17 on 2023-04-11 16:04

from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0005_auto_20230411_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgallery',
            name='image',
            field=models.ImageField(
                help_text='Will be rendered at 300px',
                upload_to='pictures/',
                verbose_name='image',
            ),
        ),
        migrations.CreateModel(
            name='EventThumbnail',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        help_text='Will be rendered at 300px',
                        upload_to=events.models.EventThumbnail.saving_path,
                        verbose_name='image',
                    ),
                ),
                (
                    'event',
                    models.ForeignKey(
                        blank=True,
                        help_text='event thumbnail',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='event_image',
                        to='events.event',
                    ),
                ),
            ],
            options={
                'verbose_name': 'event image',
                'verbose_name_plural': 'event images',
                'default_related_name': 'event_image',
            },
        ),
    ]
