# Generated by Django 3.2.17 on 2023-04-18 16:04

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0009_alter_event_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventgallery',
            options={
                'default_related_name': 'gallery_images',
                'verbose_name': 'Event Gallery Photo',
                'verbose_name_plural': 'Event Gallery Photos',
            },
        ),
        migrations.RemoveField(
            model_name='eventgallery',
            name='gallery_images',
        ),
        migrations.RemoveField(
            model_name='eventthumbnail',
            name='events',
        ),
        migrations.AddField(
            model_name='eventgallery',
            name='event',
            field=models.ForeignKey(
                blank=True,
                help_text='gallery images',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='gallery_images',
                to='events.event',
                verbose_name='gallery_images',
            ),
        ),
        migrations.AddField(
            model_name='eventthumbnail',
            name='event',
            field=models.OneToOneField(
                blank=True,
                help_text='event',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='event_image',
                to='events.event',
                verbose_name='event',
            ),
        ),
        migrations.AlterField(
            model_name='eventgallery',
            name='image',
            field=models.ImageField(
                help_text='Will be rendered at 300x300 px',
                upload_to='saving path',
                verbose_name='image',
            ),
        ),
    ]
