# Generated by Django 3.2.17 on 2023-04-19 13:37

from django.db import migrations
from django.db import models
import django.db.models.deletion

import events.models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0010_auto_20230418_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgallery',
            name='event',
            field=models.ForeignKey(
                blank=True,
                help_text='gallery images',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='gallery_images',
                to='events.event',
                verbose_name='gallery images',
            ),
        ),
        migrations.AlterField(
            model_name='eventgallery',
            name='image',
            field=models.ImageField(
                help_text='Will be rendered at 300x300 px',
                upload_to=events.models.EventGallery.saving_path,
                verbose_name='image',
            ),
        ),
        migrations.AlterField(
            model_name='eventthumbnail',
            name='event',
            field=models.OneToOneField(
                blank=True,
                help_text='main image',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='event_image',
                to='events.event',
                verbose_name='main image',
            ),
        ),
    ]
