# Generated by Django 3.2.17 on 2023-04-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0011_auto_20230419_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(
                default='000_000', unique=True, verbose_name='slug'
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(
                max_length=20, unique=True, verbose_name='title'
            ),
        ),
    ]
