# Generated by Django 3.2.17 on 2023-04-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0012_auto_20230419_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(
                help_text='format: yyyy-mm-dd hh:mm',
                verbose_name='date & time',
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_offline',
            field=models.BooleanField(
                default=False, verbose_name='is offline'
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(
                default='000_000',
                help_text='tag slug',
                unique=True,
                verbose_name='slug',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(
                help_text='tag title',
                max_length=20,
                unique=True,
                verbose_name='title',
            ),
        ),
    ]
