# Generated by Django 3.2.17 on 2023-04-21 20:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0014_auto_20230421_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(
                help_text='Describe your event',
                max_length=300,
                verbose_name='description',
            ),
        ),
    ]
