# Generated by Django 3.2.17 on 2023-04-21 20:42

from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0015_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(
                help_text='Users who subscribed to the event',
                related_name='users',
                to=settings.AUTH_USER_MODEL,
                verbose_name='members',
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(
                help_text='Select appropriate tags for your event',
                related_name='tags',
                to='events.Tag',
                verbose_name='tags',
            ),
        ),
    ]
