# Generated by Django 3.2.17 on 2023-04-22 03:21

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0016_auto_20230421_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_verified',
            field=models.BooleanField(
                default=False, verbose_name='is verified'
            ),
        ),
    ]
