# Generated by Django 3.2.17 on 2023-04-22 03:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0017_tag_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
